# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uca < Formula
  desc "Update multiple coding-agent CLIs with one command"
  homepage "https://github.com/chhoumann/uca"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chhoumann/uca/releases/download/v0.4.1/uca_0.4.1_darwin_amd64.tar.gz"
      sha256 "efbe1a0f97981c5039fe5554e833b6b0bad1ecf1043bd5781f4de2e0d5855500"

      define_method(:install) do
        bin.install "uca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chhoumann/uca/releases/download/v0.4.1/uca_0.4.1_darwin_arm64.tar.gz"
      sha256 "5800faeb0eb3ecf2bf335e8b24581083e5235d469939600caf65f0cb1b23bab1"

      define_method(:install) do
        bin.install "uca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chhoumann/uca/releases/download/v0.4.1/uca_0.4.1_linux_amd64.tar.gz"
      sha256 "a95225e2065730adb89aeede1516ad1d85a2f256629af3c3dfa249059cb1c920"
      define_method(:install) do
        bin.install "uca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chhoumann/uca/releases/download/v0.4.1/uca_0.4.1_linux_arm64.tar.gz"
      sha256 "206c6c172f564f9cba093fcd6b9eb4313e9d9d2b303263a62a01c69f6e7bd112"
      define_method(:install) do
        bin.install "uca"
      end
    end
  end
end
