# This file was generated by GoReleaser. DO NOT EDIT.
cask "uca" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "7229bb66ffda118edd24b0106086d740371a387411435fe4a7e772a6394f7090"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef285106feeec129cf8a14fefd457572e80568944e9be4de1b3022fe1bec9f00"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8608a44db0af7a7b68763a8c40b93d8943b63550eaa94c3786921d3e8d5a6404"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "99970aa9d67b7c7e8be43cb090567bb1534774dda24046ea76179c20bfaaba67"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_linux_arm64.tar.gz"
    end
  end

  name "uca"
  desc "Update multiple coding-agent CLIs with one command"
  homepage "https://github.com/chhoumann/uca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uca"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uca"]
    end
  end

  # No zap stanza required

end
