# This file was generated by GoReleaser. DO NOT EDIT.
cask "uca" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "adc8cbf984aef282ad3b902b1b06aaaabf237ac993668ca0dd8e3b4f1d211e42"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7dde745230638ecf3be987805d7bc3b0eb5342d3009a759d557a64a7d6251e5c"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fd2cf9f787a4df31d70ac2613da5c8abf229f89ae9033b0774d0243a337b82b"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c78bf25cc185c39b1c94e88c478de62409a47682fa0d4f9bebf7e67a6c093bd8"
      url "https://github.com/chhoumann/uca/releases/download/v#{version}/uca_#{version}_linux_arm64.tar.gz"
    end
  end

  name "uca"
  desc "Update multiple coding-agent CLIs with one command"
  homepage "https://github.com/chhoumann/uca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uca"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uca"]
    end
  end

  # No zap stanza required

end
